namespace Flat_Server.Database {
	using Dapper;
	using Npgsql;

	public class DatabaseException : Exception {
		public DatabaseException() : base() { }
		public DatabaseException(string message) : base(message) { }
		public DatabaseException(string message, Exception innerException)
			: base(message, innerException) { }
	}

	internal static class Database {
		private static string connectionString = "";

		public static NpgsqlConnection Connection {
			get {
				try {
					NpgsqlConnection connection = new(connectionString);
					connection.Open();
					return connection;
				} catch (NpgsqlException) { throw new DatabaseException("Не удалось подключиться к базе данных."); }
			}
		}

		public static void Connect(string connectionString) {
			Database.connectionString = connectionString;

			try {
				using var connection = Connection;

				connection.Execute(@"
CREATE TABLE IF NOT EXISTS users (
	user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	login VARCHAR(64) NOT NULL UNIQUE,
	password_hash VARCHAR(512) NOT NULL,
	nickname VARCHAR(64),
	user_role VARCHAR(16) NOT NULL,
	CONSTRAINT CHK_login CHECK (login ~ '^[a-zA-Z0-9]+$' AND LENGTH(login) >= 3),
	CONSTRAINT CHK_password_hash CHECK (password_hash ~ '^[a-zA-Z0-9]+$'),
	CONSTRAINT CHK_nickname CHECK (nickname ~ '^[a-zA-Zа-яА-Я0-9_],+( [a-zA-Zа-яА-Я0-9_]+)*$' AND LENGTH(nickname) >= 3),
	CONSTRAINT CHK_user_role CHECK (user_role IN ('administrator', 'moderator', 'user'))
);

CREATE TABLE IF NOT EXISTS categories (
	category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	category_name VARCHAR(64) NOT NULL UNIQUE,
	CONSTRAINT CHK_category_name CHECK (category_name ~ '^(?! )[a-zA-Zа-яА-ЯёЁ0-9:]+(?: [a-zA-Zа-яА-ЯёЁ0-9:]+)*(?<! )$' AND LENGTH(category_name) >= 3)
);

CREATE TABLE IF NOT EXISTS games (
	game_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	game_name VARCHAR(64) NOT NULL,
	icon BYTEA,
	description TEXT,
	approved BOOLEAN NOT NULL DEFAULT FALSE,
	likes INT NOT NULL DEFAULT 0,
	dislikes INT NOT NULL DEFAULT 0,
	CONSTRAINT CHK_game_name CHECK (game_name ~ '^(?! )[a-zA-Zа-яА-ЯёЁ0-9:]+(?: [a-zA-Zа-яА-ЯёЁ0-9:]+)*(?<! )$' AND LENGTH(game_name) >= 3),
	CONSTRAINT CHK_description CHECK (description ~ '^[a-zA-Zа-яА-ЯёЁ0-9\s.,!?;:«»""''()- ]+$' AND LENGTH(description) >= 3)
);

CREATE TABLE IF NOT EXISTS games_categories (
	games_categories_entry_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	game_id INT NOT NULL,
	category_id INT NOT NULL,
	CONSTRAINT FK_game_id FOREIGN KEY (game_id) REFERENCES games(game_id),
	CONSTRAINT FK_category_id FOREIGN KEY (category_id) REFERENCES categories(category_id),
	CONSTRAINT UQ_game_category UNIQUE(game_id, category_id)
);

CREATE TABLE IF NOT EXISTS game_images (
	games_images_entry_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	game_id INT NOT NULL,
	image BYTEA NOT NULL,
	CONSTRAINT FK_game_id FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS game_comments (
	comment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	game_id INT NOT NULL,
	user_id INT NOT NULL,
	likes INT NOT NULL DEFAULT 0,
	dislikes INT NOT NULL DEFAULT 0,
	comment_text TEXT NOT NULL,
	comment_date DATE NOT NULL DEFAULT CURRENT_DATE,
	CONSTRAINT FK_game_id FOREIGN KEY (game_id) REFERENCES games(game_id),
	CONSTRAINT FK_user_id FOREIGN KEY (user_id) REFERENCES users(user_id),
	CONSTRAINT CHK_comment_text CHECK (comment_text ~ '^[a-zA-Zа-яА-ЯёЁ0-9\s.,!?;:«»""''()- ]+$' AND LENGTH(comment_text) >= 3)
);

CREATE TABLE IF NOT EXISTS game_versions (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	game_id INT NOT NULL,
	version_name VARCHAR(16) NOT NULL,
	version_data BYTEA NOT NULL,
	approved BOOLEAN NOT NULL DEFAULT FALSE,
	CONSTRAINT CHK_version_name CHECK (version_name ~ '^\d+(\.\d+)*$'),
	CONSTRAINT UQ_game_version UNIQUE (game_id, version_name)
);
				");
			} catch (PostgresException) { throw new DatabaseException("Не удалось инициализировать базу данных."); }
			catch (NpgsqlException) { throw new DatabaseException("Не удалось подключиться к базе данных.");  }
		}
	}
}
